# Generated by Django 3.2.11 on 2022-02-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Mobile No')),
                ('birth_date', models.DateField(verbose_name='Date Of Birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail Id')),
                ('address', models.TextField(verbose_name='Address')),
                ('profile_state', models.CharField(choices=[('new', 'NEW'), ('active', 'ACTIVE'), ('rejected', 'REJECTED'), ('assigned', 'ASSIGNED'), ('closed', 'CLOSED')], default='new', max_length=80, verbose_name='Profile State')),
                ('reference', models.CharField(choices=[('agent', 'AGENT'), ('other', 'SOCIAL')], default='other', max_length=80, verbose_name='Our Reference')),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='Your profile Pic')),
                ('reference_details', models.CharField(max_length=30, verbose_name='Reference Provider')),
                ('language', models.TextField(verbose_name='Language Know')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Institute Name')),
                ('standard', models.CharField(max_length=100, verbose_name='Standard Name')),
                ('percentage', models.FloatField(verbose_name='Percentage')),
                ('year', models.DateField(verbose_name='Year')),
                ('course', models.TextField(null=True, verbose_name='Special Course')),
                ('CGPA', models.FloatField(null=True, verbose_name='Your CGPA')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField(null=True, verbose_name='Skill Level')),
                ('technical_skill', models.TextField(verbose_name='Technical Skills')),
                ('soft_skill', models.TextField(verbose_name='Soft Skill')),
                ('Project', models.TextField(verbose_name='Project Details')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_skill', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=60, verbose_name='Company Name')),
                ('latter', models.ImageField(max_length=60, null=True, upload_to='', verbose_name='Company Experience Latter')),
                ('start_date', models.DateField(verbose_name='Join Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('role', models.CharField(max_length=80, null=True, verbose_name='Previous Company Role')),
                ('New_role', models.CharField(default='developer', max_length=80, verbose_name='Looking For Role')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='candidate.candidateprofile')),
            ],
        ),
    ]
