# Generated by Django 3.2.11 on 2022-02-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Mail Id'),
        ),
    ]
