# Generated by Django 3.2.11 on 2022-02-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidateprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='CGPA',
            new_name='cgpa',
        ),
    ]
